[project]
name = "stripe-card-checker"
version = "1.0.0"
description = "Flask API for credit card checking via Stripe"
authors = [{ name = "angle-1666" }]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "flask",
    "requests",
    "beautifulsoup4",
    "Faker"
]
